# Include file for cleaning 'EVTYPE' data

WeatherType <- c('AVALANCHE')
df_StormData_Subset$EVTYPE <- fSREVTYPE('AVALANCE', WeatherType)

WeatherType <- c('BLIZZARD')
df_StormData_Subset$EVTYPE <- fSREVTYPE('BLIZZARD/WINTER STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GROUND BLIZZARD', WeatherType)

WeatherType <- c('COLD')
df_StormData_Subset$EVTYPE <- fSREVTYPE('AGRICULTURAL FREEZE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD AND WET CONDITIONS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD TEMPERATURE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD WAVE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD WEATHER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD/WIND CHILL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD/WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DAMAGING FREEZE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EARLY FROST', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXTENDED COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXTREME COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXTREME COLD/WIND CHILL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXTREME WIND CHILL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXTREME WINDCHILL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FREEZE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FREEZING DRIZZLE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FREEZING RAIN/SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FREEZING SPRAY', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FROST', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FROST/FREEZE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FROST\\FREEZE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HARD FREEZE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LOW TEMPERATURE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RECORD COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('UNSEASONABLE COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('UNSEASONABLY COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER STORMS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER WEATHER MIX', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER WEATHER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER WEATHER/MIX', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTRY MIX', WeatherType)

WeatherType <- c('SNOW')
df_StormData_Subset$EVTYPE <- fSREVTYPE('ACCUMULATED SNOWFALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('BLOWING SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD AND SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FALLING SNOW/ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY LAKE SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW AND HIGH WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW AND STRONG WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW SHOWER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW SQUALLS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/BLIZZARD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/BLIZZARD/AVALANCHE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/FREEZING RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/HIGH WINDS & FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/SQUALLS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW/WINTER STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOWPACK', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SNOW-SQUALLS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LAKE-EFFECT SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHT SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHT SNOWFALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RECORD SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW ACCUMULATION', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW AND HEAVY SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW AND ICE STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW AND ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW FREEZING RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW SQUALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW SQUALLS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/ BITTER COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/ ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/BLOWING SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/FREEZING RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/HEAVY SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/ICE STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/SLEET', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/SLEET/FREEZING RAIN', WeatherType)

WeatherType <- c('ICE')
df_StormData_Subset$EVTYPE <- fSREVTYPE('BLACK ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GLAZE ICE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GLAZE/ICE STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE AND SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE FLOES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE JAM FLOOD (MINOR', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE JAM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE ON ROAD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE STORM/FLASH FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE/STRONG WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICY ROADS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SLEET/ICE STORM', WeatherType)

WeatherType <- c('HAIL')
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 0.75', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 075', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 100', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 125', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 150', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 175', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 200', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 275', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 450', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL 75', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL DAMAGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAILSTORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SMALL HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM HAIL', WeatherType)

WeatherType <- c('FOG')
df_StormData_Subset$EVTYPE <- fSREVTYPE('DENSE FOG', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FOG AND COLD TEMPERATURES', WeatherType)

WeatherType <- c('HEAT')
df_StormData_Subset$EVTYPE <- fSREVTYPE('ABNORMAL WARMTH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DROUGHT/EXCESSIVE HEAT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXCESSIVE HEAT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXTREME HEAT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAT WAVE DROUGHT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAT WAVE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAT WAVES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEATS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RECORD HEAT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RECORD/EXCESSIVE HEAT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RECORD/HEAT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('UNSEASONABLY WARM AND DRY', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('UNSEASONABLY WARM', WeatherType)

WeatherType <- c('FIRE')
df_StormData_Subset$EVTYPE <- fSREVTYPE('BRUSH FIRE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FOREST FIRES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GRASS FIRES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WILD FIRES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WILD/FOREST FIRE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WILD/FOREST FIRES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WILDFIRE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WILDFIRES', WeatherType)

WeatherType <- c('LIGHTNING')
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING AND HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING AND THUNDERSTORM WIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING FIRE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING INJURY', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING THUNDERSTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING WAUSEON', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING.', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGHTNING/HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LIGNTNING', WeatherType)

WeatherType <- c('DRYNESS')
df_StormData_Subset$EVTYPE <- fSREVTYPE('ABNORMALLY DRY', WeatherType)

WeatherType <- c('RAIN')
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXCESSIVE RAINFALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FREEZING RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FREEZING RAIN/SLEET', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY MIX', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN AND FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN/HIGH SURF', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN/LIGHTNING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN/SEVERE WEATHER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN/SMALL STREAM URBAN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAIN/SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAINS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SHOWER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS/HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RAIN/SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RAIN/WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RAINSTORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RECORD RAINFALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORRENTIAL RAINFALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('UNSEASONAL RAIN', WeatherType)

WeatherType <- c('FLOOD')
df_StormData_Subset$EVTYPE <- fSREVTYPE('BEACH EROSION', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('BREAKUP FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COASTAL FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COASTAL FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COASTAL FLOODING/EROSION', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DAM BREAK', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EROSION/CSTL FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD - HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD FROM ICE JAMS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD/ STREET', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD/', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD/FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD/LANDSLIDE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOODING/FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOODING/THUNDERSTORM WI', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOODS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD & HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD FLASH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD/FLASH FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD/FLASH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD/FLASHFLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD/RAIN/WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOOD/RIVER FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOODING/HEAVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLOODS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY RAINS/FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SURF COASTAL FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ICE JAM FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LAKE FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LAKESHORE FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MAJOR FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MINOR FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RAPIDLY RISING WATER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RIVER AND STREAM FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RIVER FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RIVER FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RURAL FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SMALL STREAM FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOWMELT FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TIDAL FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN AND SMALL STREAM FLOODIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN FLOODS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN SMALL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN/SMALL STREAM FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN/SMALL STREAM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('URBAN/SML STREAM FLD', WeatherType)

WeatherType <- c('LANDSLIDE')
df_StormData_Subset$EVTYPE <- fSREVTYPE('FLASH FLOOD LANDSLIDES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LANDSLIDES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('LANDSLUMP', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MUD SLIDE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MUD SLIDES URBAN FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MUD SLIDES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MUDSLIDE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MUDSLIDES', WeatherType)

WeatherType <- c('DAMPNESS')
df_StormData_Subset$EVTYPE <- fSREVTYPE('ABNORMALLY WET', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COOL AND WET', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('EXCESSIVE WETNESS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY MIX', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY PRECIPITATION', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MIXED PRECIP', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MIXED PRECIPITATION', WeatherType)

WeatherType <- c('MARINE ACCIDENT')
df_StormData_Subset$EVTYPE <- fSREVTYPE('MARINE MISHAP', WeatherType)

WeatherType <- c('ROUGH SEAS')
df_StormData_Subset$EVTYPE <- fSREVTYPE('ASTRONOMICAL HIGH TIDE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COASTAL SURGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SEAS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SURF AND WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SURF', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SURF/HIGH SURF', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH SEAS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH SURF', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH SWELLS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH TIDES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WATER', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WAVES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND AND SEAS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RIP CURRENT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RIP CURRENTS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('RIP CURRENTS/HEAVY SURF', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('ROUGH SURF', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SURF', WeatherType)

WeatherType <- c('STRONG WINDS')
df_StormData_Subset$EVTYPE <- fSREVTYPE('COASTAL STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('COASTALSTORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DOWNBURST', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DRY MICROBURST', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DRY MIRCOBURST WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GUSTNADO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GUSTY WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GUSTY WIND/HVY RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GUSTY WIND/RAIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('GUSTY WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL/WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HAIL/WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HEAVY SWELLS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND 48', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND DAMAGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND/BLIZZARD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND/HEAVY SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WIND/SEAS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS HEAVY RAINS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS/', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS/COASTAL FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS/COLD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HIGH WINDS/SNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MARINE HIGH WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MARINE STRONG WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MARINE THUNDERSTORM WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MARINE TSTM WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MICROBURST WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('MICROBURST', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('NON-SEVERE WIND DAMAGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SEVERE THUNDERSTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SEVERE THUNDERSTORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SEVERE THUNDERSTORMS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SEVERE TURBULENCE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('SNOW/HIGH WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('STORM FORCE WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('STORM SURGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('STORM SURGE/TIDE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('STRONG WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('STRONG WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUDERSTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDEERSTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERESTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSNOW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM DAMAGE TO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND (G40)', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND 60 MPH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND 65 MPH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND 65MPH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND 98 MPH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND G50', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND G52', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND G55', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND G60', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND TREES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND.', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND/ TREE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND/ TREES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND/AWNING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND/HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WIND/LIGHTNING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS 13', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS 63 MPH', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS AND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS G60', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS LIGHTNING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS.', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS/ FLOOD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS/FLOODING', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS/FUNNEL CLOU', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS/HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS/HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDS53', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDSHAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINDSS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM WINS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORMS WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORMS WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORMS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORMW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTORMWINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERSTROM WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNDERTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('THUNERSTORM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TROPICAL STORM ALBERTO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TROPICAL STORM DEAN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TROPICAL STORM GORDON', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TROPICAL STORM JERRY', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TROPICAL STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND (G35)', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND 55', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND 65)', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND DAMAGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND G58', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WIND/HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTM WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TSTMW', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TUNDERSTORM WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WIND DAMAGE', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WIND STORM', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WIND', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WIND/HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WINTER STORM HIGH WINDS', WeatherType)

WeatherType <- c('HURRICANE')
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE EDOUARD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE EMILY', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE ERIN', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE FELIX', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE GORDON', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE OPAL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE OPAL/HIGH WINDS', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE/TYPHOON', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('HURRICANE-GENERATED SWELLS', WeatherType)

WeatherType <- c('TORNADO')
df_StormData_Subset$EVTYPE <- fSREVTYPE('COLD AIR TORNADO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('FUNNEL CLOUD', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNADO F0', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNADO F1', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNADO F2', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNADO F3', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNADOES, TSTM WIND, HAIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNADOES', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('TORNDAO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WHIRLWIND', WeatherType)

WeatherType <- c('WATERSPOUT')
df_StormData_Subset$EVTYPE <- fSREVTYPE('DUST DEVIL WATERSPOUT', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WATERSPOUT TORNADO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WATERSPOUT-', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WATERSPOUT/ TORNADO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WATERSPOUT/TORNADO', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('WATERSPOUT-TORNADO', WeatherType)

WeatherType <- c('DUST STORM')
df_StormData_Subset$EVTYPE <- fSREVTYPE('DUST DEVIL', WeatherType)
df_StormData_Subset$EVTYPE <- fSREVTYPE('DUST STORM/HIGH WINDS', WeatherType)

WeatherType <- c('HYPERTHERMIA')
df_StormData_Subset$EVTYPE <- fSREVTYPE('HYPERTHERMIA/EXPOSURE', WeatherType)

WeatherType <- c('HYPOTHERMIA')
df_StormData_Subset$EVTYPE <- fSREVTYPE('HYPOTHERMIA/EXPOSURE', WeatherType)

WeatherType <- c('UNKNOWN')
df_StormData_Subset$EVTYPE <- fSREVTYPE('?', WeatherType)
